import { StyleSheet } from "react-native";
import { Chofer } from '../interfaces/appInterfaces';

export const styles = StyleSheet.create({
    globalMargin: {
        marginHorizontal: 20
    },
    container: {
        flex: 1,
        backgroundColor: '#f9fafb',
        padding: 16,
        alignContent: 'center',
    },
    card: {
        borderTopWidth: 0,
        borderLeftWidth: 0,
        borderRightWidth: 0,
        borderBottomWidth: 0,
        paddingTop: 10,
        paddingStart: 20,
        paddingEnd: 20,
        paddingBottom: 20,
        borderRadius: 6,
        borderColor: '#c79807',
        elevation: 2,
        backgroundColor: 'white',
        marginTop:5,
        marginBottom: 2
    },
    horizontal: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        padding: 10,
    },
    Menutitle: {
        marginTop: 50,
        fontSize: 25,
        marginBottom: 5,
        fontWeight: 'normal',
        color: 'black',
    },
    BarMenuTitle: {
        borderBottomColor: '#006110',
        borderBottomWidth: 4,
        width: 100   
    },
    title: {
        marginTop: 10,
        fontSize: 25,
        marginBottom: 5,
        fontWeight: 'normal',
        color: 'black',
    },
    subtitle: {
        fontSize: 20,
        marginBottom: 5,
        fontWeight: 'bold',
        color: 'gray'
    },
    titleTable: {
        backgroundColor: '#a47d06',
        color: 'white',
        fontSize: 20,
        paddingLeft: 4,
        paddingRight: 4,
        paddingTop:2,
        paddingBottom:2,
        marginRight: 2
    },
    item: {
        backgroundColor: '#ededed',
        padding: 20,
        marginVertical: 2,
        marginHorizontal: 10,
        borderRadius: 20,
      },
    inputField: {
        marginTop: 15,
        width: 300,
        height: 50,
        backgroundColor: '#fff',
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderColor: '#ccc',
        borderWidth: 1,
        borderRadius: 15, 
        fontSize: 18,
        flex: 1,
        color: 'black'
    },
    tipoDocumento:{
        marginTop: 15,
        height: 50,
        paddingVertical: 10,
        fontSize: 16,
        marginLeft: 10,
        marginRight: 10,
        alignItems: "center",
        backgroundColor : "white",
        borderColor: 'gray',
        borderWidth: 0.5,
        borderRadius: 8,
        paddingHorizontal: 8,
        flex:1,
        color: 'black'
    },
    numDocumento: {
        marginTop: 15,
        height: 50,
        paddingVertical: 10,
        fontSize: 16,
        marginLeft: 10,
        marginRight: 10,
        alignItems: "center",
        backgroundColor: 'white',
        borderColor: 'gray',
        borderWidth: 0.5,
        borderRadius: 8, 
        paddingHorizontal: 8,
        flex: 1,
        color: 'black'
    },
    fechaRecepcion: {
        marginTop: 15,
        height: 50,
        paddingVertical: 10,
        fontSize: 16,
        marginLeft: 10,
        marginRight: 10,
        alignItems: "center",
        backgroundColor: 'white',
        borderColor: 'gray',
        borderWidth: 0.5,
        borderRadius: 8, 
        paddingHorizontal: 8,
        flex: 1,
        color: 'black'
    },
    proveedor:{
        marginTop: 15,
        height: 50,
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderColor: '#ccc',
        borderWidth: 1,
        borderRadius: 10, 
        fontSize: 16,
        flex: 4,
        marginLeft: 10,
        marginRight: 10,
        alignItems: "center",
        backgroundColor : "white",
        elevation: 2,
        color: 'black'
    },
    origen:{
        marginTop: 15,
        height: 50,
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderColor: '#ccc',
        borderWidth: 1,
        borderRadius: 10, 
        fontSize: 16,
        flex: 1,
        marginLeft: 10,
        marginRight: 10,
        alignItems: "center",
        backgroundColor : "white",
        elevation: 2,
        color: 'black'
    },
    destino:{
        marginTop: 15,
        height: 50,
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderColor: '#ccc',
        borderWidth: 1,
        borderRadius: 10, 
        fontSize: 16,
        flex: 1,
        marginLeft: 10,
        marginRight: 10,
        alignItems: "center",
        backgroundColor : "white",
        elevation: 2,
        color: 'black'
    },
    predio: {
        marginTop: 15,
        height: 55,
        backgroundColor: 'white',
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderColor: '#ccc',
        borderWidth: 1,
        borderRadius: 5, 
        fontSize: 16,
        flex: 1,
        marginLeft: 10,
        marginRight: 10,
        color: 'black'
    },
    rol: {
        marginTop: 15,
        height: 55,
        backgroundColor: 'white',
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderColor: '#ccc',
        borderWidth: 1,
        borderRadius: 5, 
        fontSize: 16,
        flex: 1,
        marginLeft: 10,
        marginRight: 10,
        color: 'black'
    },
    tipoMadera:{
        marginTop: 15,
        height: 50,
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderColor: '#ccc',
        borderWidth: 1,
        borderRadius: 10, 
        fontSize: 16,
        flex: 1,
        marginLeft: 10,
        marginRight: 10,
        alignItems: "center",
        backgroundColor : "white",
        elevation: 2,
        color: 'black'
    },
    madera:{
        marginTop: 15,
        height: 50,
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderColor: '#ccc',
        borderWidth: 1,
        borderRadius: 10, 
        fontSize: 16,
        flex: 1,
        marginLeft: 10,
        marginRight: 10,
        alignItems: "center",
        backgroundColor : "white",
        elevation: 2,
        color: 'black'
    },
    recepcionista:{
        marginTop: 15,
        height: 50,
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderColor: '#ccc',
        borderWidth: 1,
        borderRadius: 10, 
        fontSize: 16,
        flex: 4,
        marginLeft: 10,
        marginRight: 10,
        alignItems: "center",
        backgroundColor : "white",
        elevation: 2,
        color: 'black'
    },
    tipoFSC:{
        marginTop: 15,
        height: 50,
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderColor: '#ccc',
        borderWidth: 1,
        borderRadius: 10, 
        fontSize: 16,
        flex: 1,
        marginLeft: 10,
        marginRight: 10,
        alignItems: "center",
        backgroundColor : "white",
        elevation: 2,
        color: 'black'
    },
    codeFSC: {
        marginTop: 15,
        height: 50,
        paddingVertical: 10,
        fontSize: 16,
        marginLeft: 10,
        marginRight: 10,
        alignItems: "center",
        backgroundColor: 'white',
        borderColor: 'gray',
        borderWidth: 0.5,
        borderRadius: 8, 
        paddingHorizontal: 8,
        flex: 1,
        color: 'black'
    },
    rutTransportista:{
        marginTop: 15,
        height: 50,
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderColor: '#ccc',
        borderWidth: 1,
        borderRadius: 10, 
        fontSize: 16,
        flex: 4,
        marginLeft: 10,
        marginRight: 10,
        alignItems: "center",
        backgroundColor : "white",
        elevation: 2,
        color: 'black'
    },
    camion: {
        marginTop: 15,
        height: 55,
        backgroundColor: 'white',
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderColor: '#ccc',
        borderWidth: 1,
        borderRadius: 5, 
        fontSize: 16,
        flex: 1,
        marginLeft: 10,
        marginRight: 10,
        color: 'black'
    },
    carro: {
        marginTop: 15,
        height: 55,
        backgroundColor: 'white',
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderColor: '#ccc',
        borderWidth: 1,
        borderRadius: 5, 
        fontSize: 16,
        flex: 1,
        marginLeft: 10,
        marginRight: 10,
        color: 'black'
    },
    Chofer:{
        marginTop: 15,
        height: 50,
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderColor: '#ccc',
        borderWidth: 1,
        borderRadius: 10, 
        fontSize: 16,
        flex: 4,
        marginLeft: 10,
        marginRight: 10,
        alignItems: "center",
        backgroundColor : "white",
        elevation: 2,
        color: 'black'
    },
    inputDisabled: {
        marginTop: 15,
        height: 55,
        backgroundColor: '#d3d3d3',
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderColor: '#ccc',
        borderWidth: 1,
        borderRadius: 5, 
        fontSize: 16,
        flex: 1,
        marginLeft: 10,
        marginRight: 10,
        color: 'black'
    },
    buttonGuardar: {
        borderWidth: 2,
        borderColor: '#006110',
        paddingHorizontal: 20,
        paddingVertical: 5,
        borderRadius: 5,
        backgroundColor: '#006110',
        alignItems: 'center',
        fontSize: 15,
        fontWeight: 'bold',
        width: 150

    },
    buttonGuardarText: {
        color: 'white',
        fontSize: 15
    },
    buttonCancelar: {
        borderWidth: 2,
        borderColor: '#f38d8d',
        paddingHorizontal: 20,
        paddingVertical: 5,
        borderRadius: 5,
        backgroundColor: '#f38d8d',
        alignItems: 'center',
        fontSize: 15,
        fontWeight: 'bold',

    },
    buttonCancelarText: {
        color: 'white',
        fontSize: 15
    },
    buttonEliminar: {
        borderWidth: 2,
        borderColor: '#e24c4c',
        paddingHorizontal: 20,
        paddingVertical: 5,
        borderRadius: 5,
        backgroundColor: '#e24c4c',
        alignItems: 'center',
        fontSize: 20,
        fontWeight: 'bold',

    },
    buttonEliminarText: {
        color: 'white',
        fontSize: 20

    },
    buttonAgregar: {
        borderWidth: 2,
        borderColor: '#22c55e',
        paddingHorizontal: 20,
        paddingVertical: 5,
        borderRadius: 5,
        backgroundColor: '#22c55e',
        fontSize: 15,
        fontWeight: 'bold',
        marginRight:20,
        marginBottom:12,
        width: 150
    },
    buttonAgregarText: {
        color: '#f9fafb',
        fontSize: 20,
        textAlignVertical: 'center'

    },
    buttonDetalle: {
        borderWidth: 2,
        borderColor: '#3b82f6',
        paddingHorizontal: 20,
        paddingVertical: 5,
        borderRadius: 5,
        backgroundColor: '#3b82f6',
        alignItems: 'center',
        fontSize: 15,
        fontWeight: 'bold',
        width: 180

    },
    buttonDetalleText: {
        color: 'white',
        fontSize: 15
    },
    buttonEliminarItem: {
        borderRadius: 40,
        backgroundColor: '#e24c4c',
        borderColor: '#e24c4c',
        borderWidth: 2,
        width: 40,
        height: 40,
        textAlignVertical: 'center'
    },
    inputFieldIOS: {
        borderBottomColor: 'black',
        borderBottomWidth: 2,
        paddingBottom: 4
    },
    buttonContainer: {
        alignItems: 'center',
        marginTop: 50
    },
    row: {
        //flex: 1,
        flexDirection: "row"
    },
    inputSelect: {
        flex: 1,
        width: 20,
        marginLeft: 10,
        marginRight: 10,
        marginTop: 10,
        height: 20,
        alignItems: "center",
        backgroundColor : "white",
        elevation: 2,
        borderRadius: 10,
    },
    dropdown: {
        height: 50,
        borderColor: 'gray',
        borderWidth: 0.5,
        borderRadius: 8,
        paddingHorizontal: 8,
        flex:1
      },
      icon: {
        marginRight: 5,
      },
      label: {
        position: 'absolute',
        backgroundColor: 'white',
        left: 22,
        top: 8,
        zIndex: 999,
        paddingHorizontal: 8,
        fontSize: 14,
        color: 'black'
      },
      placeholderStyle: {
        fontSize: 16,
      },
      selectedTextStyle: {
        fontSize: 16,
      },
      iconStyle: {
        width: 20,
        height: 20,
      },
      inputSearchStyle: {
        height: 40,
        fontSize: 16,
      }, 
      diametro:{
        marginTop: 15,
        fontWeight: 'bold'
      },   
      cantDiametro: {
        marginTop: 8,
        height: 35,
        backgroundColor: 'white',
        paddingVertical: 2,
        paddingHorizontal: 3,
        borderColor: '#ccc',
        borderWidth: 1,
        borderRadius: 5, 
        fontSize: 12,
        flex: 1,
        marginLeft: 5,
        marginRight: 5,
    },    
    m3: {
      marginTop: 8,
      height: 35,
      backgroundColor: 'white',
      paddingVertical: 5,
      paddingHorizontal: 3,
      borderColor: '#ccc',
      borderWidth: 1,
      borderRadius: 5, 
      fontSize: 12,
      flex: 1,
      marginLeft: 5,
      marginRight: 5,
  },    
  valorm3: {
      marginTop: 8,
      height: 35,
      backgroundColor: 'white',
      paddingVertical: 5,
      paddingHorizontal: 3,
      borderColor: '#ccc',
      borderWidth: 1,
      borderRadius: 5, 
      fontSize: 12,
      flex: 1,
      marginLeft: 5,
      marginRight: 5,
  },    
  totalDetalle: {
      marginTop: 8,
      height: 35,
      backgroundColor: 'white',
      paddingVertical: 5,
      paddingHorizontal: 3,
      borderColor: '#ccc',
      borderWidth: 1,
      borderRadius: 5, 
      fontSize: 12,
      flex: 1,
      marginLeft: 5,
      marginRight: 5,
  },
  listaHeader: {
    fontSize: 16,
    fontWeight: 'bold',
    backgroundColor: '#c89551',
    color: 'white',
    height: 50,
    textAlignVertical: 'center',
    paddingLeft: 5,
    paddingRight: 5
  },
  rowHeader: {
    fontSize: 16,
    backgroundColor: '#f1f2f3',
    color: '#785b5c',
    height: 50,
    textAlignVertical: 'center',
    paddingLeft: 5,
    paddingRight: 5
  },
  sinRegistro: {
    fontSize: 16,
    flex: 1,
    justifyContent: 'center',
    textAlign: 'center'
  },
  avatarContainer: {
    alignItems: 'center',
    marginTop: 20
  },
  avatar: {
    width: 150,
    height: 150,
    borderRadius: 100
  },
  menuContainer: {
    marginVertical: 30,
    marginHorizontal: 30
  },
  menuBoton: {
    marginVertical: 10
  },
  menuTexto: {
    fontSize: 20
  }
});